---
- hosts: local
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
      tags: [node, java, zsh]

  tasks:
    - name: java
      ansible.builtin.include_tasks: tasks/java.yml
    - name: utilities
      ansible.builtin.include_tasks: tasks/utils.yml
