---
- hosts: local
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
      tags: [node, java, zsh]
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/java.yml
    - include: tasks/node.yml
